project:
  type: website
  output-dir: ../docs

website:
  title: "PAMGuard"  
  favicon: images/PAMGuardIcon2.png
  google-analytics: 
    tracking-id: G-0N9ELT30EX
    storage: cookies
    anonymize-ip: true
  cookie-consent: 
    type: implied
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**New standard reference for PAMGuard** : [PAMGuard: Application software for passive acoustic detection, classification, and localisation of animal sounds](https://pubs.aip.org/asa/jasa/article/159/1/437/3377442/PAMGuard-Application-software-for-passive-acoustic)"
    type: dark
    position: below-navbar
  navbar:
    search: true
    logo: images/PAMGuardIcon2.png
    background: rgb(43,78, 128, 255)
    left:
#      - href: index.qmd
#        text: Home
      - text: About
        menu: 
          - text: About PAMGuard
            href: about.qmd
          - text: License
            href: license.qmd
          - text: Funding
            href: funding.qmd

          - text: Publications
            href: ./publications.qmd
          - text: Meet the team
            href: ./team/team.qmd
      - text: Users
        menu:
          - text: User Tutorials
            href: ./tutorials/tutorials.qmd
          - text: Core Modules
            href: coremodules.qmd
          - text: Plugin Modules
            href: pluginmodules.qmd
          - text: Data Export, R, Matlab, & Python
            href: matlabandr.qmd
          - text: Contact and Support
            href: contact.qmd
          - text: Online help pages
            href: ./olhelp/index.html
      - text: Download
        menu:
          - text: System Requirements
            href: systemreq.qmd
          - href: downloadsurvey.qmd
            text: PAMGuard Installers
          - href: plugins/plugins.qmd
            text: Download Plugins
          - href: ./configs/configs.qmd
            text: Configuration Files
          - href: ./rocca/rocca.qmd
            text: Rocca Classifiers
          - href: whistleclassifier.qmd
            text: Whistle Classifiers
          - href: ./deep_learning_models/deeplearningmodels.qmd
            text: Deep Learning Classifiers
      - text: Developers
        menu:
          - href: sourcecode.qmd
            text: Source Code
          - href: devmodules.qmd
            text: Develop PAMGuard Modules
          - href: addmodules.qmd
            text: Adding Core Modules
          - href: devplugins.qmd
            text: Creating Plugin Modules
          - text: PAMGuard API
            href: ./api/index.html
            target: pamguardapi
      - text: Links
        menu:
          - text: MMO Service Providers
            href: ./links/mmo.qmd
          - text: Non Governmental Organisations (NGO's)
            href: ./links/ngos.qmd
        
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/PAMGuard/PAMGuard
            target: pggitpage
          - text: Report an Issue
            href: https://github.com/PAMGuard/PAMGuard/issues
            target: pggitpage
      - icon: facebook
        menu:
          - text: Facebook
            href: https://www.facebook.com/pamguard
            target: pgfbpage
          - text: BlueSky
            href: https://bsky.app/profile/pamguard.org
            target: pgbspage

format:
  html:
    theme: default
    css: styles.css
    toc: true

editor: visual

